[package]
name = "dispersal_model_rust"
version = "0.1.0"
authors = ["Gereon A. Kaiping <gkaiping@geo.uzh.ch>"]
edition = "2018"
debug = true

[profile.release]
debug = true

[lib]
name = "model"

[[bin]]
name = "simulation"
path = "src/main.rs"

[[bin]]
name = "simple"
path = "src/simple.rs"

[[bin]]
name = "graphwriter"
path = "src/serialize_graph.rs"

[dependencies]
rand = ">=0.0.0"
rand_distr = ">=0.0.0"
rayon = ">=0.0.0"
libh3 = ">=0.0.0"
tiff = ">=0.5.0"
argparse = ">=0.0.0"
lazy_static = ">=0.0.0"
petgraph = { version = ">=0.0.0", features = ["serde-1"] }
serde = ">=0.0.0"
bincode = ">=0.0.0"
rusqlite = ">=0.0.0"
dashmap = ">=3.0.0"
